### ISSUE TITLE
request webmin

### ISSUE THREAD

**Issue by mzramna** [linuxserver/reverse-proxy-confs#100]
could be created an webmin reverseproxy configuration file,since it is very simple to be created,(https://serverfault.com/questions/443482/proxying-webmin-with-nginx)

**Comment by j0nnymoe** [comment]
We generally create proxy conf's as and when we create new containers. You're more than welcome to create the conf yourself and PR it :)

**Comment by anoma** [comment]
I would worry that use offering this infers an implicit recommendation for webmin.

Almost no one should run webmin.

https://www.cvedetails.com/vulnerability-list/vendor_id-358/Webmin.html.

**Comment by CHBMB** [comment]
In light of the above, I'm closing this.  If someone wants to submit a PR they can, but it should probably include a massive flashing siren powered disclaimer and warning.
