### ISSUE TITLE
Incorrect comment in config

### ISSUE THREAD

**Issue by wbagdon** [linuxserver/reverse-proxy-confs#103]
https://github.com/linuxserver/reverse-proxy-confs/blob/e2f4bb469effb296235bef0d42dac06f4c703a20/tt-rss.subdomain.conf.sample#L2

This is not needed if you set the `X-Forwarded-Proto` header properly
`proxy_set_header X-Forwarded-Proto $scheme;`

**Comment by aptalca** [comment]
Did you test it with the default proxy.conf on letsencrypt? The default for `X-Forwarded-Proto` is https

**Comment by wbagdon** [comment]
Ok so it's already properly set?
Then the comment is not needed at all.

**Comment by aptalca** [comment]
But did you test it?

**Comment by nemchik** [comment]
@aptalca I want to say it was me, but if I left the `proxy.conf` out it may have been intentional. Some apps don't like everything in the `proxy.conf`. Needs testing.

**Comment by wbagdon** [comment]
The whole file can be deleted now that tt-rss is deprecated

**Comment by nemchik** [comment]
The proxy sample still has value. Even though the app itself is no longer included in the active roster this is simply a proxy sample that could be used by anyone running tt-rss whether it be via the deprecated lsio image or some other image or local install without docker.
