### ISSUE TITLE
Grafana subfolder

### ISSUE THREAD

**Issue by Nosirus** [linuxserver/reverse-proxy-confs#104]
I'm trying to grafana for a live dashboard with letsencrypt without success

location ^~ /grafana {
	# enable the next two lines for http auth
	#auth_basic "Restricted";
	#auth_basic_user_file /config/nginx/.htpasswd;

	# enable the next two lines for ldap auth
	#auth_request /auth;
	#error_page 401 =200 /login;

	include /config/nginx/proxy.conf;
	resolver 127.0.0.11 valid=30s;
	set $upstream_grafana grafana;
	proxy_pass http://$upstream_grafana:3000;
}

I'm sending back to /login but with a /root display of letsencrypt

**Comment by aptalca** [comment]
Try this: https://grafana.com/docs/grafana/latest/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-grafana

**Comment by nemchik** [comment]
Grafana was one I couldn't get working well with subfolders, so there's no config sample for it. It's probably doable. Let us know what you find.

**Comment by Nosirus** [comment]
location ^~ /grafana/ {
    include /config/nginx/proxy.conf;
    rewrite  ^/grafana/$  https://DOMAIN/grafana/d/NGs8Sl-Zz/DASHBOARD?orgId=1&refresh=30s&kiosk=tv permanent;
    proxy_pass http://192.168.1.50:3000;
    
    proxy_max_temp_file_size 2048m;
	
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
and modify defaults.ini grafana

# The full public facing url
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = true

**Comment by jens1000** [comment]
This worked for me:
I have this config in /config/nginx/proxy-confs/grafana.subfolder.conf:

```
location ~/monitoring(.*)$ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app grafana;
    set $upstream_port 3000;
    set $upstream_proto http;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port$1;
}
```

And changed the root_url in /usr/share/grafana/conf/defaults.ini:
`root_url = %(protocol)s://%(domain)s/monitoring/`

The `serve_from_sub_path `variable didn't make any difference for me.

**Comment by xnaas** [comment]
I can confirm the above works as long as the correct config stuff if set on Grafana's side.

**Comment by IronicBadger** [comment]
I have used the following for `https://my.domain.com/grafana` for a couple of years now - and so far as I can remember I made no changes to `default.ini`:

```
location /grafana/ {
    resolver 127.0.0.11 valid=30s;
    set $upstream_grafana grafana;
    proxy_pass http://$upstream_grafana:3000;
    rewrite ^/grafana/(.*)$ /$1 break;
}
```

Compose snippet:

```
  - service_name: grafana
    active: true
    nginx_configs_rp_enabled: true
    nginx_configs_rp_type: subfol
    include_global_env_vars: false
    image: grafana/grafana
    container_name: grafana
    environment:
      - "GF_SERVER_ROOT_URL=https://my.domain.com/grafana"
      - "GF_SERVER_DOMAIN=https://my.domain.com/"
```

However I recently started testing Traefik - this issue is of course for nginx but reference I had to set the following ENV vars to make it work properly with Traefik.

```
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=(Host(`my.domain.com`) && PathPrefix(`/grafana`))
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    environment:
      - GF_SERVER_ROOT_URL=https://my.domain.com/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=my.domain.com
```
