### ISSUE TITLE
Airsonic creating http request on 443

### ISSUE THREAD

**Issue by Davis-A** [linuxserver/reverse-proxy-confs#105]
Issue:  
Airsonic streaming when using a subdomain redirection issue.  

When streaming via the webui on https://airsonic.myaddress.com opening a stream generates a url that looks like http://airsonic.myaddress.com:443/stream?player=5&id=176
Which nginx sees as a bad request as it's a http request on port 443.

**Comment by aptalca** [comment]
See comment on #106
