### ISSUE TITLE
Kanboard support

### ISSUE THREAD

**Issue by vinanrra** [linuxserver/reverse-proxy-confs#115]
I have been trying to create a subdomain without luck, could be good to add i tried modifing this:

This is my file, but only show default nginx
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name kanboard.*;

	include /config/nginx/ssl.conf;

    location / {

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ ^/(?:kanboard|config.php|config.default.php) {
            deny all;
        }

        location ~* /data {
            deny all;
        }

        location ~ \.php(?:$|/) {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on; # Use only if HTTPS is configured
            #include fastcgi_params;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
```

https://docs.kanboard.org/en/latest/admin_guide/url_rewriting.html

**Comment by aptalca** [comment]
That's not a reverse proxy configuration. That's for natively serving kanboard via nginx.

**Comment by vinanrra** [comment]
Them i have 0 idea, is there anyway to create a subdomain for Kanboard or anywhere to start learning?

**Comment by drizuid** [comment]
copy one of our samples and modify accordingly, join us on discord in #other-support if you'd like to discuss further. Once you have a working config, feel free to submit a PR
