### ISSUE TITLE
Anyone else having a problem, with the pihole.subfolder.conf?

### ISSUE THREAD

**Issue by STaRDoGG** [linuxserver/reverse-proxy-confs#127]
1. I'm able to access the usual http://pi.hole/admin
2. Then I renamed the `pihole.subfolder.conf.sample` to `pihole.subfolder.conf` (even copied/pasted the latest version from the repo as of today.)
3. `docker cp` it over to the LE container, and restart it
4. Visit https://my.domain.rocks:3333/pihole

I get the following error:

> [ERROR]: Unable to parse results from queryads.php: Unhandled error message (Invalid domain!)

![image](https://user-images.githubusercontent.com/1524526/74847796-52a2f600-52f8-11ea-930c-f718c0e64be9.png)

Not sure if this is useful, but a quick goggle turned up this:

https://github.com/pi-hole/pi-hole/issues/2195.

**Comment by nemchik** [comment]
Please try https://my.domain.rocks:3333/pihole/admin

**Comment by STaRDoGG** [comment]
@nemchik bingo! that worked. Looks like the .conf needs tweaking to auto redirect to the admin page?

**Comment by nemchik** [comment]
https://my.domain.rocks:3333/pihole is actually used for another reason.

| internal | proxy |
| --- | --- |
| http://pi.hole/ | https://my.domain.rocks:3333/pihole |
| http://pi.hole/admin | https://my.domain.rocks:3333/pihole/admin |
