### ISSUE TITLE
Jackett + Organizer auth + LE container?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/reverse-proxy-confs#128]
I'm not real good with these things so I don't know for sure which place to go to for the right help, but I figured that the way the LE container's proxy configs are kinda tweaked a specific way, that maybe you guys might have a better grasp on how to handle this issue?

Rather than type it all out again, I'll just link to my first post on it, I don't think they use this specific container so they might not be the right place to go to for help?:

https://github.com/causefx/Organizr/issues/1311

Can anyone help, pls?

**Comment by nemchik** [comment]
Comment out `auth_request off;` and see if that works.

**Comment by YouveGotMeowxy** [comment]
@nemchik Thanks for the help, that line is designed to stop checking authorization for those urls (via organizr). If I comment it out while leaving the other auth line enabled in the location block above it, then it'll still check auth via Organizr. 

Just to double-check though, I did comment it out and try again, but still have the same problem.

**Comment by nemchik** [comment]
Copying your config here so I don't have to go to the other page

```nginx
location ^~ /jackett {
    auth_request /auth-1;
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}

location ~ /jackett/(api|dl) {
    auth_request off; # Disable Organizr auth for the API
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}
```

**Comment by nemchik** [comment]
I know what the auth line is for. I made the jackett config in this repo (originally pulled from https://github.com/linuxserver/docker-letsencrypt/blame/ed9721289639718ebca88bfce691c2947f7ffbd7/root/defaults/proxy-confs/jackett.subfolder.conf.sample )

The two location blocks are separated and not nested so that the API location can be unaffected by the main location and you can put auth on the main location and leave the auth commented on the API location.

I believe the API location isn't being picked as the match by nginx. Please try this:

```nginx
# first go into jackett settings, set the URL Base to /jackett and restart the jackett container

location /jackett {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app jackett;
    set $upstream_port 9117;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}

location ^~ /jackett/api {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app jackett;
    set $upstream_port 9117;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}

location ^~ /jackett/dl {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app jackett;
    set $upstream_port 9117;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```

Only modify the auth in the first location.

**Comment by HalianElf** [comment]
The issue with the first block is the `^~` making it ignore the regex.

**Comment by YouveGotMeowxy** [comment]
@nemchik Thank you, that worked!

Just for the record, I wasn't trying to talk down to you about the auth line, I just didn't know whether or not you were already familiar with with what it did. :)

**Comment by nemchik** [comment]
No worries. I'm going to update the config samples. They should be included in the next release cycle.

**Comment by YouveGotMeowxy** [comment]
@HalianElf just out of curiosity then, this would have worked too?

```
location /jackett {
    auth_request /auth-1;
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}

location ^~ /jackett/(api|dl) {
    auth_request off; # Disable Organizr auth for the API
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}
```

**Comment by HalianElf** [comment]
Yes it does as I said in the Orgainzr issue you opened.
