### ISSUE TITLE
Looking for cloud9.subdomain.conf

### ISSUE THREAD

**Issue by ravers77** [linuxserver/reverse-proxy-confs#142]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by nemchik** [comment]
This is just a generic copy/paste of another sample, but if you can confirm it works I can PR it into the repo to be included in the future.

```nginx
# make sure that your dns has a cname set for cloud9 and that your cloud9 container is named cloud9

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cloud9.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app cloud9;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

**Comment by ravers77** [comment]
thank you for the quick response, but it gives me the error "502 Bad Gateway"

**Comment by j0nnymoe** [comment]
@ravers77 you need to make sure they're on the same network and your container is called `cloud9`

**Comment by ravers77** [comment]
nginx and cloud9 are on the same docker-host and my container is called "cloud9"

**Comment by j0nnymoe** [comment]
Same docker network, not host.

**Comment by nemchik** [comment]
Run `docker exec letsencrypt ping cloud9 -c2`

If that does not show you an IP address then the containers cannot see each other. If they cannot see each other the proxy will not work. You need both containers on the same user-defined bridge network running on your host.

**Comment by ravers77** [comment]
Result: "ping: bad address 'cloud9'
How do i have to configure it in docker-compose.yml? or maybe in docker?

**Comment by nemchik** [comment]
I prefer compose. Each of our images has a compose example in the readme. You can combine those into a single compose file and bring up the whole compose stack together. This should run things the way you need.

**Comment by ravers77** [comment]
I already use compose, but for every container a new compose-file

**Comment by nemchik** [comment]
You either need to look at the docker compose documentation about how to manage containers and docker networks, or my recommendation would be to put all of your compose files together into one. Having one compose file automatically handles docker networking in a very easy way that will work with these proxy configs.

**Comment by ravers77** [comment]
Proxying to cloud9 successfull. 
You can add cloud9.subdomain.conf to the project.
