### ISSUE TITLE
Looking for reverse-proxy-conf for phpmyadmin

### ISSUE THREAD

**Issue by ravers77** [linuxserver/reverse-proxy-confs#145]

**Comment by nemchik** [comment]
https://github.com/linuxserver/reverse-proxy-confs/blob/master/phpmyadmin.subdomain.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/master/phpmyadmin.subfolder.conf.sample

If you're running our letsencrypt container these files will be in the proxy-conf folder with all the other samples.

**Comment by ravers77** [comment]
oh, sorry... i didn#t updated my reverse-proxy-conf files.
but is there a docker-container for phpmyadmin from linuxserver?

**Comment by aptalca** [comment]
no, there isn't

**Comment by sarvesh-lad** [comment]
If you use subfolder it doesn't seem to work..

It redirects to after entering credentials:

https://example.net/index.php?route=/&route=%2F

And outputs:

`File not found`

Refreshing or manually accessing the URL shows the GUI (https://example.net/phpmyadmin)

Some config file editing may be needed as documented here: https://stackoverflow.com/a/44083978
