### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by crashouse** [linuxserver/reverse-proxy-confs#153]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
I tried to create a reverse proxy for mailu. Im using this image: https://hub.docker.com/r/linuxserver/letsencrypt/. They work perfectly. However, when I proceed to use the reverse proxy I get the "bad gateway" error. I will copy my configuration here. I have used the same of adminer, since in that service it works for me. I hope you can help me.

![error](https://user-images.githubusercontent.com/4247187/80084588-5c92e080-8557-11ea-8088-a8497c41238f.png)

location /adminer {
    return 301 $scheme://$host/adminer/;
}
location ^~ /adminer/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app adminer;
    set $upstream_port 8080;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

Here is the configuration used 
```


location /admin{
    return 301 $scheme://$host/admin/;
}
location ^~ /admin/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app front;
    set $upstream_port 8080;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port/admin;

}
```

**Comment by vinanrra** [comment]
Thx for copying my post at Mailu github, i hope we find something

**Comment by tobbenb** [comment]
Please use discord or our discourse forum for support issues. 
https://discourse.linuxserver.io

Issues on GitHub is reserved for bugs.
