### ISSUE TITLE
Config Request: Tiny Media Manager

### ISSUE THREAD

**Issue by adrfantini** [linuxserver/reverse-proxy-confs#161]
TMM is an extremely useful media scraper, cleaner, renamer and manager.

Here are some info on a possible Nginx config: https://github.com/romancin/tinymediamanager-docker/blob/master/README.md

The project has since moved to gitlab: https://gitlab.com/tinyMediaManager

**Comment by adrfantini** [comment]
Config request still relevant!

**Comment by j0nnymoe** [comment]
No one within the team uses this. Take our example template we provide and see if you get in working. If you get stuck, post what config you have with the error and we can help.
