### ISSUE TITLE
http2 protocol

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/reverse-proxy-confs#181]
Add http2 protocol to the config files.

like:
```
listen 443 ssl http2;
listen [::]:443 ssl http2;
```

**Comment by nemchik** [comment]
Ref:
https://www.nginx.com/blog/http2-module-nginx/#QandA
https://serverfault.com/a/765337/177096
http://mailman.nginx.org/pipermail/nginx/2015-December/049445.html

tl;dr
`http2` doesn't have any effect on `proxy_pass` directives, so it would not serve any purpose in the configs in this repo.
