### ISSUE TITLE
Add noindex header

### ISSUE THREAD

**Issue by adamradocz** [linuxserver/reverse-proxy-confs#182]
Wouldn't it be beneficial to prevent any indexing?
`add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";`

**Comment by aptalca** [comment]
It's in the readme: https://github.com/linuxserver/docker-letsencrypt#site-config-and-reverse-proxy

**Comment by adamradocz** [comment]
Oh, thanks!
Why isn't this option the default, or at least in the config file as a commented option?

**Comment by aptalca** [comment]
Because this is a webserver meant to host public sites. If you want to make them private, you can use one of the auth options and you don't need noindex
