### ISSUE TITLE
Config Request: Cockpit

### ISSUE THREAD

**Issue by MarshallCS** [linuxserver/reverse-proxy-confs#187]
I would love a working config for Cockpit. I've tried multiple sites suggested configs with no success:

https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx

https://medium.com/@r.szulist/how-to-install-and-configure-cockpit-on-cenos8-3615d503092a

https://serverfault.com/questions/681084/docker-cockpit-error-after-redirecting-with-nginx

Thanks!

**Comment by NICHOLAS85** [comment]
I've had success with the following:
Editing `/etc/cockpit/cockpit.conf` according to https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx#make-cockpit-proxy-aware

The following `cockpit.subdomain.conf` file
```nginx
server {
	  listen 443 ssl;
	  listen [::]:443 ssl;
	  
	  server_name cockpit.*;
	  
	  include /config/nginx/ssl.conf;
	  
	  client_max_body_size 0;
	  
	  location / {
		    include /config/nginx/proxy.conf;
		    include /config/nginx/resolver.conf;
		    
		    set $upstream_app cockpit;
		    set $upstream_port 9090;
		    set $upstream_proto https;
		    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
			
			proxy_buffering off;		    

		    # Pass ETag header from Cockpit to clients.
		    # See: https://github.com/cockpit-project/cockpit/issues/5239
		    gzip off;
	  }
}
```

This file just follows the format of the other sample files, adding in the required configuration from https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-nginx#virtual-host-file and removing duplicate options already set in the include lines. 

Depending on how you're running things you'll likely need to change the `set $upstream_app cockpit` line to the IP address where cockpit is running.

I just learned how to set up linuxserver/swag the other day and don't have a real understanding of how everything works. This was mostly trial and error to get to work correctly. If someone with real experience could check the conf file I'd be open to creating a pr.
