### ISSUE TITLE
proxy.conf - where is it?

### ISSUE THREAD

**Issue by bbrendon** [linuxserver/reverse-proxy-confs#192]
Many of these configs reference `/config/proxy.conf`. I don't see it anywhere or documented in the readme.  Can someone enlighten me?

**Comment by nemchik** [comment]
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf this file should end up in your `/config` volume when you run the `linuxserver/swag` (previously `linuxserver/letsencrypt`) container. Specifically it should be at `/config/nginx/proxy.conf`
