### ISSUE TITLE
Gotify login error

### ISSUE THREAD

**Issue by zedred79** [linuxserver/reverse-proxy-confs#195]
I have a problem with Gotify, the gotify.subdomain.conf file is the standard one, I haven’t changed it (not even a line).
I can access the gotify home page on gotify.mydomain.com, but when I try to login it always gives me the “login failed” error, if I try locally without the proxy I have no login problem.

Do you have any ideas?

**Comment by iurab** [comment]
I have the same issue. Locally the connection works, through proxy it doesn't work.
I'm using the template part of the commit 54ede40.
