### ISSUE TITLE
Podman

### ISSUE THREAD

**Issue by omarc1492** [linuxserver/reverse-proxy-confs#215]
I'm not sure if this would be considered a feature for this project, but I've used these samples and docker-swag to create a reverse proxy in front of GitLab using `podman` and podman user defined networks `cni`.

I believe support for [Podman](https://podman.io/) would be easy to implement.

**Comment by Roxedus** [comment]
1. This is the wrong place for issues regarding https://github.com/linuxserver/docker-swag
2. We only test on Docker
3. Neither are you actually describing an issue

**Comment by omarc1492** [comment]
1. I'm not saying there is an issue regarding docker-swag. The only reason I mentioned docker-swag is because it uses these files to provide reverse proxy configuration samples.
2. I know this is tested only on Docker, I was trying to state that adding support for Podman is relatively easy and requires almost no change. At most it could just be a small mention in the docs somewhere...
3. Agreed, there is no issue. Just a possible feature suggestion.

**Comment by Roxedus** [comment]
My point is that this is the completely wrong place for such request.


How would Podman, a daemonless, non-root system work with our containers that simply require root?

**Comment by omarc1492** [comment]
You can do rootfull networking by using sudo, `sudo podman`.
Even containers running as rootless are still able to communicate from container to container.

I'm using CentOS 8, which comes with `podman` installed by default. What would be a better place to add such a request? It works for me and if I can help someone than great.

**Comment by j0nnymoe** [comment]
We don't currently have any plans to support any fork/replacement for docker, If our containers do work with podman, then great. There has been some discussion on it here previously: https://github.com/linuxserver/docker-nzbget/issues/64 .
