### ISSUE TITLE
Is the sonarr config secure?

### ISSUE THREAD

**Issue by emanuelem** [linuxserver/reverse-proxy-confs#218]
I am using [sonarr.subdomain.conf](https://github.com/linuxserver/reverse-proxy-confs/blob/master/sonarr.subdomain.conf.sample) with auth enabled (Authelia, but the question applies to any other auth method).

However I noticed that the auth settings only apply to location /, not to `location ~ (/sonarr)?/api`. In fact I can access `https://sonarr.my.url/sonarr/api` bypassing any auth.

I was wondering if this is safe or if it allows anyone to make API calls to my Sonarr installation.

**Comment by j0nnymoe** [comment]
It's safe as they'd need your API key to make calls to it.
