### ISSUE TITLE
ruTorrent RPC security?

### ISSUE THREAD

**Issue by ImjuzCY** [linuxserver/reverse-proxy-confs#222]
I'm using authelia for authentication on ruTorrent. Is there any security on the /RPC path? It doesn't need any API key to access the ruTorrent through RPC, isn't there a security problem there? Is adding a basic http authentication with .htpasswd file the only way to secure this? 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
Thanks for the heads up. I don't use rutorrent, so I assumed the api endpoint required an api key, but it seems in this case it does not. So you are correct that the config we ship does leave it unprotected. I'll go ahead and add the auth options to it so users can enable whichever they prefer, with a default deny all.
