### ISSUE TITLE
Organizr auth and new 2.1 api

### ISSUE THREAD

**Issue by arnishow** [linuxserver/reverse-proxy-confs#224]
Hi,

organizr-auth.subfolder.conf.sample does not work anymore with new Organizr v2.1 which is going to be the next stable branch very soon.
	
More information here: https://docs.organizr.app/books/setup-features/page/organizr-20--%3E-21-migration-guide

**Comment by Roxedus** [comment]
We are aware, and will do the needed changes closer to release

**Comment by arnishow** [comment]
Thanks for that information.
