### ISSUE TITLE
nextcloud not working properly

### ISSUE THREAD

**Issue by mzramna** [linuxserver/reverse-proxy-confs#239]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

raspian

started the letsencrypt with working options and heimdall,(with everyting except next cloud works fine so, i supose it is properly setup) and add nextcloud subfolder,ps: same happends into letsencrypt,nginx and swag,so the prolem should be here

`nginx: [emerg] "proxy_max_temp_file_size" directive invalid value in /config/nginx/proxy-confs/nextcloud.subfolder.conf:35`

using volume mount

just by commenting out the line 35 evryting works just fine,but seems that should be used,accord to nextcloud forums and other referencies,so could be missing any app or anything inside container

**Comment by cravas** [comment]
It's strange that there's no reply about this:
Just change the default value from 2048m to 1024m

Same goes for "nextcloud.subdomain.conf"
armhf doesn't like that high value, ;)

**Comment by ProgramComputer** [comment]
Opened pull request #343 to change to default.
