### ISSUE TITLE
Authentication issues with FreshRSS as a subdomain

### ISSUE THREAD

**Issue by czebiniak** [linuxserver/reverse-proxy-confs#242]
I use an UnRAID docker setup for SWAG and FreshRSS

This looks to be a proxy cookie issue in the swag config, I am using the exact config as shown in the [example](https://github.com/linuxserver/reverse-proxy-confs/blob/master/freshrss.subdomain.conf.sample).

**Comment by czebiniak** [comment]
I have discovered the same issue is happening in Heimdall, I am wondering if this is due to a recent update, started noticing the issue about a month ago

**Comment by czebiniak** [comment]
What info do you require? I see this was moved to Insufficient info

**Comment by czebiniak** [comment]
Nevermind, I'll just figure it out by myself, and won't post the answer when I find it since no one is responding

**Comment by aptalca** [comment]
fwiw, not only you didn't fill out the issue template, you didn't even describe your actual issue other than vague statements such as `Authentication issues` and `looks to be a proxy cookie issue`
