### ISSUE TITLE
Add Sample Config for Snipe-It subdomain

### ISSUE THREAD

**Issue by stevo028** [linuxserver/reverse-proxy-confs#262]
Would really appreciate a sample config for Snipe-it, really new to this and not sure what is required. 
https://docs.linuxserver.io/images/docker-snipe-it

**Comment by k2trf** [comment]
AFAIK the issues board on here is for bugs, and there is a discourse/discord for support such as this. But I'm just a random person whom wandered upon this looking for something else.

Here's what I've got setup, works so long as you have a cname set in dns for it & you are using the lsio/snipe-it container. Worth mentioning I'm also using the "robots f-off" line (the add_header call above the include for ssl.conf) so nothing of mine gets indexed (hopefully).

If you're using subfolders, you'll need to tweak it slightly - use your other configs/samples as templates (worst that can happen if you do it wrong in any given proxy conf is it doesn't work). This/I use subdomains, on a custom domain I own.

## Version 2020/12/09
# make sure that your dns has a cname set for snipe-it

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name snipeit.*;

    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app snipe-it;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
