### ISSUE TITLE
Config Request: Synology Diskstation and Services

### ISSUE THREAD

**Issue by macgiver510** [linuxserver/reverse-proxy-confs#263]
1st of all...
Thank you to the team for all you have done so far!

2nd:
I would like to run a Synology Diskstation behind an NGINX Reverse Proxy and need a config sample.

I really struggle with it as some services do not work. And I really need help with that.

What is not working
For example, a "Surveillance Station" of this Synology device does not provide a live stream of the cams.
Or the "Photo Station" is also not working as expected.
"Filestation"....
all is not working.

I cannot remember what exact config had which effect, but I was at some point where I was able to login, but after calling the mentioned Apps, There was no active WebPage.

I need these services, as my Phone is connection to the Photo station to back up my pics from the smartphone to the diskstation
The surveillance station is also used and my wife is running the default app to check the cams.

Thanks

**Comment by EVOTk** [comment]
Hello , In README : 

> NOTE: We avoid providing samples that publicly expose server management software (ex: syno, qnap, unraid, proxmox, esxi, etc). Pull requests to add samples for this category of applications will not be accepted.

https://github.com/linuxserver/reverse-proxy-confs#how-to-use-these-reverse-proxy-configs

**Comment by nemchik** [comment]
You can use the template file to create a proxy for pretty much anything, but we won't be including it in the repo.

Thanks.
