### ISSUE TITLE
Incorrect <container_name> in _template.subdomain.conf.sample#11

### ISSUE THREAD

**Issue by Erriez** [linuxserver/reverse-proxy-confs#282]
The following line is incorrect:

**/config/nginx/proxy-confs/_template.subdomain.conf.sample**
```yaml
    server_name <container_name>.*;
```

It mentions the container name, but after some debugging I discovered that this is the subdomain.

Proposal is to replace `container_name` with `subdomain`. I can provide a MR when someone can confirm this.

Thanks!

**Comment by Roxedus** [comment]
It is not incorrect, as you can see in all the samples, we use the container name as the subdomain.

**Comment by Erriez** [comment]
There are two things:
1. The DNS subdomain configuration type CNAME
2. Container name

For the `code-server` container I configured DNS name `vcode.mydomain.nl` at my provide and container name `code-server` in `docker-compose.yml`. As you can see, different names.

For this configuration I've configured:

```
    # Listening to DNS subdomain dot anydomain dot any root:
    server_name vcode.*;  # This is not the container name

    # Container name in `docker-compose.yml`:
    set $upstream_app code-server;
```

The `_template.subdomain.conf.sample` uses the term `server_name <container_name>.*;` which incorrect.

NGINX documentation: http://nginx.org/en/docs/http/server_names.html

**Comment by Roxedus** [comment]
It is correct in the sense that we want to keep the subdomain and service/container name the same across our samples. Our [documentation](https://docs.linuxserver.io/general/swag#subdomain-proxy-conf) covers what the server_name does, if a user want to customize their setup.

**Comment by aptalca** [comment]
The template is not meant to be a teaching tool for nginx. It is a template for _our_ preset proxy confs. _We use_ the container name as server name subdomain. If somebody wants to submit a new proxy conf for an app or service, they need to use that template we have, with the structure we picked.

Thanks

**Comment by Erriez** [comment]
> It is correct in the sense that we want to keep the subdomain and service/container name the same across our samples.

I understand and I agree. 

My problem is that it took me a lot of time to figure out how to change listening to a different DNS subdomain. The [documentation](https://docs.linuxserver.io/general/swag#subdomain-proxy-conf) is not clear for me. That's the reason why `server_name <container_name>.*;` is really confusing.

**Comment by aptalca** [comment]
The documentation clearly states:

`server_name heimdall.*;`
Only destination addresses that match heimdall.* will match this server block.
