### ISSUE TITLE
Nextcloud Webdav not working with subdomain

### ISSUE THREAD

**Issue by Erriez** [linuxserver/reverse-proxy-confs#293]
Nextcloud Webdav is not accessible because CardDav and CalDav are missing in `reverse-proxy-confs/nextcloud.subdomain.conf.sample`

The following Nextcloud documentation describes how to connect with Ubuntu to Nextcloud via WebDav:
https://docs.nextcloud.com/server/21/user_manual/en/files/access_webdav.html?highlight=webdav#accessing-files-using-linux

by using the address `webdav://example.com/nextcloud/remote.php/dav/files/USERNAME/` in Nautilus. This does not work, because the following NGINX configuration for CardDev and Caldav is missing:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#nginx

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name nextcloud.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app nextcloud;
        set $upstream_port 443;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # CardDav
        location /.well-known/carddav {
            return 301 $upstream_proto://$upstream_app/remote.php/dav;
        }

        # CalDav
        location /.well-known/caldav {
            return 301 $upstream_proto://$upstream_app/remote.php/dav;
        }

        proxy_max_temp_file_size 2048m;
    }
}
````

With the fix above, a the username and password is prompted and can be used to access Nextcloud data:

![ConnectServer](https://user-images.githubusercontent.com/8849873/107984576-7dd22b00-6fc8-11eb-8118-9c48b5bda4b1.png)

However, I'm not able to get Windows up and running which is probably a different problem.

**Comment by aptalca** [comment]
Those are in the nextcloud default conf: https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/default#L45-L50

**Comment by Erriez** [comment]
Thanks for your fast reply. You're right, this is already part of that configuration file. I'll check tomorrow if it is a possible configuration problem in my setup. Stay tuned.

**Comment by Erriez** [comment]
Finally I've it up and running without the CardDav and CalDav modification as aptalca mentioned.

For Windows, the service `WebClient` must be automatically started, otherwise the `Error code: 0x8007004 The network name cannot be found.` is shown. This service is `Stopped` by default.
