### ISSUE TITLE
help synology photo station config

### ISSUE THREAD

**Issue by hongho55** [linuxserver/reverse-proxy-confs#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

can you make synology nas config?? 

i made synology dsm config. it is working. but it's not access Photo station.

how can i do?

![image](https://user-images.githubusercontent.com/40291055/56116061-d933cc00-5f9f-11e9-8af7-184c68fb9c41.png)

**Comment by j0nnymoe** [comment]
Sorry - no one within the team uses Synology.

**Comment by hongho55** [comment]
ok i solved.. and opened a port of photo station.
