### ISSUE TITLE
Adding Foundry VTT subdomain config sample

### ISSUE THREAD

**Issue by Sakujakira** [linuxserver/reverse-proxy-confs#303]
Adding Foundry VTT config sample

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Adding Foundry subdomain config for convenience.

**Comment by tobbenb** [comment]
You don't need to add both an issue and a PR at the same time. It's enough with the PR.
