### ISSUE TITLE
Hide "Welcome to your swag instance"

### ISSUE THREAD

**Issue by musklor** [linuxserver/reverse-proxy-confs#306]
Hi, I'd like to hide the page "Welcome to your swag instance", any idea?

Thanks for all your work.

**Comment by Roxedus** [comment]
Define hide.

**Comment by musklor** [comment]
> Define hide.

How? Where?

**Comment by Roxedus** [comment]
What do you mean with hide? preventing it to show up? replacing it? dancing monkeys?

**Comment by jpkeane** [comment]
In the folder you have mapped to config, you can edit the index.html file in the www folder to something more to your liking.

The www folder is the documents folder for the default site.

**Comment by musklor** [comment]
> In the folder you have mapped to config, you can edit the index.html file in the www folder to something more to your liking.
> 
> The www folder is the documents folder for the default site.

Excellent, thanks.

**Comment by musklor** [comment]
> What do you mean with hide? preventing it to show up? replacing it? dancing monkeys?

I think I'll put some dancing monkeys on my web page

**Comment by Roxedus** [comment]
Replacing it with dancing monkeys, I like your style
