### ISSUE TITLE
Q: Why isn't authelia.conf included in nextcloud.subdomain.conf.sample?

### ISSUE THREAD

**Issue by smokemyshoes** [linuxserver/reverse-proxy-confs#308]
Hi

I am just wondering why your nextcloud.subdomain.conf and nextcloud.subfolder.conf doesn't have any entries for authelia.conf like the majority of your other conf.sample's?

I'm troubleshooting a "502 Bad Gateway" when trying to reach my nextcloud/nextcloud container behind swag which is protected by authelia and one of the things I've stumbled upon is that in the [Authelia docs. example for nextcloud](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html#protected-endpoint-1), the nextcloud.subdomain.conf included both an auth.conf and an authelia.conf.

Thanks in advance.

**Comment by Roxedus** [comment]
Because double auth just introduces problems, and anyone venturing to use Authelia with Nextcloud should be able to put the required stuff in place themselves. It is excluded for support reasons.

**Comment by smokemyshoes** [comment]
> 
> 
> Because double auth just introduces problems, and anyone venturing to use Authelia with Nextcloud should be able to put the required stuff in place themselves. It is excluded for support reasons.

Thanks for your reply. Just to really spell it out, are you saying that nextcloud does not support Authelias method of passing authentication information? And that I would be better of excluding nextcloud.mydomain.com from authelia authentication?

Thanks in advance...

**Comment by Roxedus** [comment]
I am not saying that, I am saying that most users don't use that feature of Authelia, and afaik that requires a modified setup of what's in the config we ship anyway.

**Comment by smokemyshoes** [comment]
Ok, thanks alot.
