### ISSUE TITLE
Tubesync: help or config request

### ISSUE THREAD

**Issue by luisalrp** [linuxserver/reverse-proxy-confs#310]
I am trying to publish [tubesync](https://github.com/meeb/tubesync) app through SWAW but I constantly get the following response:

> Bad Request
> Contradictory scheme headers

The OS is unRAID where there is installed SWAG and Authelia, which both of them work good.

The proxy-conf file I setup is named tubesync.subdomain.conf and the content is:
`server {
	    listen 443 ssl;
	    listen [::]:443 ssl;

	    server_name ts.*;

	    include /config/nginx/ssl.conf;

	    client_max_body_size 0;

	    # enable for Authelia
	    include /config/nginx/authelia-server.conf;

	    location / {
	      # checks for static file, if not found proxy to app
	      try_files $uri @proxy_to_app;
	    }

	    location @proxy_to_app {
	      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	      proxy_set_header X-Forwarded-Proto $scheme;
	      proxy_set_header Host $http_host;
	      # we don't want nginx trying to do something clever with
	      # redirects, we set the Host: header above already.
	      proxy_redirect off;
	      # enable for Authelia
	      include /config/nginx/authelia-location.conf;
	      include /config/nginx/proxy.conf;
	      resolver 127.0.0.11 valid=30s;
	      set $upstream_app tubesync;
	      set $upstream_port 4848;
	      set $upstream_proto http;
	      proxy_pass $upstream_proto://$upstream_app:$upstream_port;
	    }
}
`

Any idea what I'm doing wrong? Thanks!

**Comment by ksurl** [comment]
I'm getting the same issue though I followed the template instead of making my own conf file. the tubesync dev said nothing should be interfering on the app's side. tubesync actually runs its own nginx reverse proxy for localhost:8080 to container:4848. I'm not knowledgeable enough to pick apart any contradictory configs in proxy.conf and the nginx.conf in tubesync (check the repo).

**Comment by TheSpad** [comment]
It's probabably the `proxy_set_header X-Forwarded-Proto $scheme` which exists in both and will likely be mismatched as on the front-end swag will be connecting over https but on the backend it's probably https only.

**Comment by ksurl** [comment]
but there are plenty of other (probably most) applications that connect over http and have swag use https on the front end. why would it conflict here?

**Comment by Roxedus** [comment]
You said why, yourself. 
> tubesync actually runs its own nginx reverse proxy for localhost:8080

**Comment by ksurl** [comment]
I commented out the include proxy.conf and pasted the contents directly into the tubesync conf and by process of elimination after adding each one by one, it is the `proxy_set_header X-Forwarded-Proto https;` that breaks it. it works otherwise if commented out

**Comment by ngInit** [comment]
For anyone running into this issue still, I only needed to comment out the `proxy_set_header X-Forwarded-Ssl on;` setting found in the `proxy.conf` import to get it working.
