### ISSUE TITLE
Changes to the Organizr API from Version 2.1 requiers new location block

### ISSUE THREAD

**Issue by Sakujakira** [linuxserver/reverse-proxy-confs#321]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Since Organizr Version 2.1, they require a new Location Block. 
Source: https://docs.organizr.app/books/setup-features/page/organizr-20--%3E-21-migration-guide

Since im a noob, if it comes to Webserver configuration, here is an example which seems to be working:

```
location /api/v2 {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app organizr;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        #try_files $uri /api/v2/index.php$is_args$args;

}
```

Can anyone confirm? Then i could prepare an Mergerequest.

**Comment by Roxedus** [comment]
You do not handle this on the reverse proxy, the container itself manages this.
