### ISSUE TITLE
home assistant conf file issue

### ISSUE THREAD

**Issue by bn7thebh** [linuxserver/reverse-proxy-confs#339]
I'm trying to use your default homeassistant.subdomain.conf file but im not running the home assistant as a docker im running it as a VM I did replace the streaming app with the local ip address and the api part the site give me bad gateway 

any help please ? 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by tobbenb** [comment]
Please use discord or Discourse for support. 

https://www.linuxserver.io/support
