### ISSUE TITLE
Overseerr subfolder configuration

### ISSUE THREAD

**Issue by CoderLD-LX** [linuxserver/reverse-proxy-confs#340]
I'm interested in proxying Overseerr as a subfolder and not having go through my DNS provider with the Subdomain configuration. I have seen the configutation that Overseerr has posted for a subfolder but I'm not comfortable enough with NGINX (and how it's been configured within SWAG) to create a subfolder for it. Is there something in the configuration that overseerr needs which makes a subfolder through SWAG not possible or practical?

**Comment by Roxedus** [comment]
Not possible.
