### ISSUE TITLE
Sonarr "Failed to load series from API"

### ISSUE THREAD

**Issue by KnifeFed** [linuxserver/reverse-proxy-confs#345]
I'm running swag on Unraid 6.9.2 using `sonarr.subdomain.conf` and Cloudflare DNS for my own domain.

When having a Sonarr tab open, it frequently errors out with the message "Failed to load series from API" after being idle for a little while. A page refresh fixes it.

The very sparse information I've found when googling the issue [hints at](https://old.reddit.com/r/sonarr/comments/j7x7rp/i_get_failed_to_load_series_from_api_on_sonarr/g888932/) it having something to do with how the nginx reverse proxy timeout is configured, which makes sense because it doesn't happen when connecting via ip:port. I'm also using Radarr with `radarr.subdomain.conf` and it does not seem to have a similar issue.

That's as far as my knowledge goes for this so any help would be appreciated. Thanks.

**Comment by Roxedus** [comment]
Check the swag logs, are any of your configs out of date?

**Comment by KnifeFed** [comment]
Nope, they're all up to date.

**Comment by Roxedus** [comment]
Can you post the proxy.conf in your swag install, as i cant reproduce this.

**Comment by KnifeFed** [comment]
I just checked and my `proxy.conf` is identical to: https://raw.githubusercontent.com/linuxserver/docker-swag/012e729f4923529e2e41ef4cecdf8da572c22307/root/defaults/proxy.conf

My Sonarr container is from binhex, if that makes a difference.

**Comment by BrunoVicious** [comment]
So here is what I found on sonarr's forums. It seems that the page takes longer to load and nginx is timing out before it can load completely. When I use the new config under swag I get the "Failed to load series from API" error. However I had saved my old config from the older letsencrypt container you made awhile back and when I use that one with swag I no longer get that error. Something you added in the new config is creating that error for sonarr.

https://forums.sonarr.tv/t/failed-to-load-series-from-api-error/27377

`old config (the one that works)

# make sure that your dns has a cname set for sonarr and that your sonarr container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name sonarr.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_sonarr binhex-sonarr;
        proxy_pass http://$upstream_sonarr:8989;
    }

    location ~ (/sonarr)?/api {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_sonarr binhex-sonarr;
        proxy_pass http://$upstream_sonarr:8989;
   }
}

`

`new config (the one that doesn't work)

## Version 2021/05/18
# make sure that your dns has a cname set for sonarr and that your sonarr container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name sonarr.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app binhex-sonarr;
        set $upstream_port 8989;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location ~ (/sonarr)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app sonarr;
        set $upstream_port 8989;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

   }
}

`
