### ISSUE TITLE
"proxy_redirect" directive is duplicate in /config/nginx/proxy-confs/freshrss.subdomain.conf:39

### ISSUE THREAD

**Issue by jokerigno** [linuxserver/reverse-proxy-confs#361]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hi,

after an upgrade my freshrss instance no longer works. Here's the error I found multiple times in the logs making also other webservices unavailable:

"nginx: [emerg] "proxy_redirect" directive is duplicate in /config/nginx/proxy-confs/freshrss.subdomain.conf:39"

I just simply use the sample with no changes ad all and I have a subdomain like freshrss.mydomain.it.

Host OS is Unraid with swag container ( no tuning).

Thank you in advance!

**Comment by aptalca** [comment]
It's due to a recent undocumented change in nginx. Please remove the `proxy_redirect off;` directives from your proxy confs and let us know if you experience any issues with those apps (or if they work just fine). We *think* it's safe to remove those but it still needs to be tested.

Thanks

**Comment by ksurl** [comment]
missed one. plex also has it.

**Comment by aptalca** [comment]
that one's not in the same location block as the proxy.conf so it doesn't cause the dupe issue

**Comment by jokerigno** [comment]
removeing the `proxy_redirect off;` did the trick. Thank you!
