### ISSUE TITLE
Nextcloud trusted domain arrays

### ISSUE THREAD

**Issue by bconn98** [linuxserver/reverse-proxy-confs#374]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

OS:  Ubuntu Linux 20.04

I am adding nextcloud to my setup, and am experiencing some issues. I believe in part it is due to the following comment.
"Also don't forget to add your domain name to the trusted domains array. It should look somewhat like this:"  
  
This is not clear to me what file I should be looking to update. I do understand what it is asking but just am not sure where the file is found.  
  
I would suggest updating this to make it more clear in the future.

**Comment by Roxedus** [comment]
It's still referencing the same `config.php`, as the part above the array part.

**Comment by bconn98** [comment]
For reference this is my config.php, I do not see anything resembling that.  
  
```
<?php
$CONFIG = array (
  'memcache.local' => '\OC\Memcache\APCu',
  'datadirectory' => '/data',
  'trusted_proxies' => ['swag'],
  'overwritewebroot' => '/nextcloud',
  'overwrite.cli.url' => 'https://<my-ip-addr>/nextcloud',
  );  
```

**Comment by bconn98** [comment]
@Roxedus Please see my most recent comment as I do not believe this is correctly marked resolved.

**Comment by aptalca** [comment]
https://help.nextcloud.com/t/howto-add-a-new-trusted-domain/26

**Comment by bconn98** [comment]
Thank you! I suggest adding a default of that to the base container.
