### ISSUE TITLE
configuring for multiple instances of the same container

### ISSUE THREAD

**Issue by shersch** [linuxserver/reverse-proxy-confs#376]
I have multiple instances of the linuxserver qbittorrent container running.  i'd like to use swag to put authelia in front of each of them.  they each have their own subdomain, and none of the containers are actually called "qbittorrent".  i'm not sure how to edit the conf files for that.  any assistance would be much appreciated!

**Comment by nemchik** [comment]
If you've got all the containers on the same user defined network in bridge mode you can rename multiple copies of the qbittorrent proxy sample file (ex: `qbit1.subdomain.conf` and `qbit2.subdomain.conf`) and edit the files to change the server address at the top to whatever subdomain you want as the address, and change the upstream app variables to the names of your containers.

**Comment by shersch** [comment]
so in this block, should i change "/qbittorrent" on the first line to also be the name of my container name?

```
location ~ (/qbittorrent)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app qbittorrent;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        rewrite /qbittorrent(.*) $1 break;
```

**Comment by nemchik** [comment]
If you're doing subfolder proxies, the first line of what you posted can be any name you want. For the sake of keeping things simple, if you want to access the container using its name, then yes, set that line to the name of your container.

More importantly, inside that location is `set $upstream_app qbittorrent;` and that needs to be the container name.

**Comment by shersch** [comment]
@nemchik it works!  thank you so much!
