### ISSUE TITLE
Mylar(3) upstream_app 

### ISSUE THREAD

**Issue by keitocorp** [linuxserver/reverse-proxy-confs#377]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

I was reinstalling my containers on a new server and noticed that mylar wasn't showing its GUI after adding the `mylar.subfolder.conf`. I know there are 2 versions (mylar, and Mylar3) right now. Seeing as LinuxServer.io has marked mylar as depricated i've been using Mylar3 for a while now (on a different server with different setup).

I got a 404 when i tried to load Mylar3 with http://HOSTNAME/mylar (already added to the http_root). After some digging i realised that the conf is based on the previous mylar (i think?). So changing the Upstream_app to Mylar3 fixed my problem.

I don't know whether the confs are intended for the old version or that they haven't been updated to the new Mylar3 yet.

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app mylar3;            ## added the '3' at the end
    set $upstream_port 8090;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

Just wanted to put it out there.

**Comment by aptalca** [comment]
We just never created a proxy conf specifically for mylar3. It would have both the upstream app and the server name as mylar3. This one is for the old version. Like you discovered, one can update the upstream app to match the container name of the new one and it works

**Comment by keitocorp** [comment]
THanks for the confirmation Aptalca, appreciate all the hard work you guys do!
