### ISSUE TITLE
Trailing slash consistency

### ISSUE THREAD

**Issue by sambartik** [linuxserver/reverse-proxy-confs#389]
Hello, I have been thinking that all locations should have consistent trailing slash behaviour. 

As of right now, it is a mess: some services do have trailing slashes and some of them don't. I propose that we hold a discussion after which we can stick to one standard and make all current and future configs slash-consistent. 

What do you think?

**Comment by Roxedus** [comment]
We do have consistency, it's no trailing slash. If a service is written in a way that it need a trailing slash, we set up a redirect.

**Comment by nemchik** [comment]
@sambartik if you have a specific example in mind from this repo that we may have overlooked feel free to bring it up here. We don't mind to address it.
