### ISSUE TITLE
requestrr.subfolder.conf

### ISSUE THREAD

**Issue by BK-STAR77** [linuxserver/reverse-proxy-confs#404]
Hello everyone

I try to settings requestrr with no-ip but it don't work anyone have the good settings

requestrr.subfolder.conf

```
location /requestrr {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app requestrr;
    set $upstream_port 4545;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```

thank for your help

**Comment by j0nnymoe** [comment]
Describe "doesn't work" - what happens?

It's likely that it doesn't work with subfolders. Would explain why we only provide a subdomain proxy.

**Comment by BK-STAR77** [comment]
> Describe "doesn't work" - what happens?
> 
> It's likely that it doesn't work with subfolders. Would explain why we only provide a subdomain proxy.

OK I understand. Thank your response
