### ISSUE TITLE
jackett.subfolder.conf = page can’t be found

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/reverse-proxy-confs#411]
## the error
```
This 192.168.0.1 page can’t be found
No webpage was found for the web address: https://192.168.0.1/jackett/
HTTP ERROR 404
```
### jackett is reachable via qbittorrent
where 192.168.0.1 is my docker server and when I go to 192.168.0.1 I see the swag page and 192.168.0.1/qbittorrent I could use qbittorrent which is able to use jackett because in config/qbittorrent/qBittorrent/nova3/engines/jackett.json I specified 
`"url": "http://jackett:9117"` which is routed properly through the docker. 
![image](https://user-images.githubusercontent.com/5204724/145696679-7ffa1e46-69cf-40c1-bbb8-32ff774a7d52.png)

### swag ping jackett
inside swag, I'm also able to ping jackett
![image](https://user-images.githubusercontent.com/5204724/145696691-4cd56c0b-122e-42e1-bb28-eb105bf61595.png)

#### and the config are fine
I literally just `cp jacket.subfolder.conf.sample jacket.subfolder.conf` and reload/restart swag
##### docker logs swag
![image](https://user-images.githubusercontent.com/5204724/145696724-a5c31cac-71a3-4348-bf4c-50e7fa5b75bf.png)

##### cat swag/log/nginx/error.log
![image](https://user-images.githubusercontent.com/5204724/145696852-e9ca6a8d-1e13-4b5c-84fa-108be1f4ba6d.png)

### jacket.subdomain.conf is working
- when I use jackett subdomain it work
- when I use jackett subfolder it end with this page

So this is way I'm opening an issue here because I think it is inside the nginx config 

- I found this https://github.com/Jackett/Jackett/wiki/Reverse-Proxy but when I compare with your config (proxy.conf + jackett.subfolder.conf) I don't really see an issue.

## So what else I should try ? :)

**Comment by aminroosta** [comment]
I'm facing the exact same issue.

**Comment by nemchik** [comment]
Have you set the URL Base option in Jackett (per the instructions in the proxy file)?
https://github.com/linuxserver/reverse-proxy-confs/blob/18d9c74e399e5ded14975576fb0b6b42a33e6f7f/jackett.subfolder.conf.sample#L2 (also the first thing noted on the jackett wiki page you linked)

**Comment by aminroosta** [comment]
I'm such an idiot!
Updating the "Base path override" in the UI to "/jackett" works flawlessly.
Thanks a bunch @nemchik  ❤️ 

For anyone else reading this, I didn't try it, but setting `"BasePathOverride": "/jackett"` in the config file,
probably does the same thing (`/config/Jackett/ServerConfig.json`).

<img width="735" alt="Screenshot 2022-01-05 at 3 14 57 PM" src="https://user-images.githubusercontent.com/2920178/148232474-d515126a-eea7-4384-8e0c-196bcd4c1a89.png">
