### ISSUE TITLE
Vaultwarden Websocket doesn't work with subfolder

### ISSUE THREAD

**Issue by noaho** [linuxserver/reverse-proxy-confs#418]
Hi, 

With https://github.com/linuxserver/reverse-proxy-confs/blob/master/bitwarden.subfolder.conf.sample and (docker environment variable) DOMAIN=https://$HOST_HOSTNAME/bitwarden

I get working bitwarden, but no websocket. In Network inspector in firefox I see 

<img width="407" alt="Screen Shot 2022-01-18 at 11 10 26 am" src="https://user-images.githubusercontent.com/7568339/149869949-670731aa-a822-4953-b222-9f3b9d2d0345.png">

However, remove the environment variable DOMAIN= and change to 
https://github.com/linuxserver/reverse-proxy-confs/blob/master/bitwarden.subdomain.conf.sample

and now I get a working websocket.. 

<img width="407" alt="Screen Shot 2022-01-18 at 11 00 55 am" src="https://user-images.githubusercontent.com/7568339/149868991-e37ed758-d7dd-46fb-8f84-10951dd0d0fb.png">

I'm not sure how to troubleshoot this further.. Is there some logging I can enable on SWAG that will show why it's getting error 400 for the subfolder example?

**Comment by nemchik** [comment]
Can you try replacing these lines:

```nginx
location /notifications/hub {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app bitwarden;
    set $upstream_port 3012;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}

location /notifications/hub/negotiate {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app bitwarden;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```

with:

```nginx
location /bitwarden/notifications/hub {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app bitwarden;
    set $upstream_port 3012;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}

location /bitwarden/notifications/hub/negotiate {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app bitwarden;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```
in your subfolder conf? https://github.com/linuxserver/reverse-proxy-confs/blob/6681cadaa7141ba631fd206c6ae7a733a34ea67f/bitwarden.subfolder.conf.sample#L29-L47
(note that if you've named the container `vaultwarden` then you'd want `set $upstream_app vaultwarden;` in both locations)
And then set `DOMAIN=https://$HOST_HOSTNAME/bitwarden` and see if that combination works?

**Comment by noaho** [comment]
That change appears to work, Cheers!

Btw: I notice the latest commit added a new file separately for vaultwarden.. But I think the bitwarden file is also for vaultwarden? Not sure if this is a mistake?
https://github.com/linuxserver/reverse-proxy-confs/commit/6681cadaa7141ba631fd206c6ae7a733a34ea67f

**Comment by TheSpad** [comment]
They're functionally identical but the new one was added for convenience so as not to confuse users who came to Vaultwarden after its rename and the old one has been retained for use with the official Bitwarden container(s).

**Comment by nemchik** [comment]
> That change appears to work, Cheers!

Thanks for confirming. I'll check a few things on my end and get changes published soon. I'll link to my PR to close this issue.

**Comment by nemchik** [comment]
Try one of these:
https://github.com/linuxserver/reverse-proxy-confs/blob/be77f99548d6e208fdd98f1faf74481130e79ee9/bitwarden.subfolder.conf.sample
https://github.com/linuxserver/reverse-proxy-confs/blob/be77f99548d6e208fdd98f1faf74481130e79ee9/vaultwarden.subfolder.conf.sample
