### ISSUE TITLE
Under reverse-proxy-confs, a few lines required per Jellyfin documentation are missing from jellyfin.subdomain.conf.sample

### ISSUE THREAD

**Issue by emes81** [linuxserver/reverse-proxy-confs#440]
Some admin tools for playback info in Jellyfin were missing in my install; I managed to fix this by 1) migrating to swag and 2) editing jellyfin.subdomain.conf to conform with the Jellyfin documentation:

https://jellyfin.org/docs/general/networking/letsencrypt.html

The version currently at https://github.com/linuxserver/reverse-proxy-confs/blob/master/jellyfin.subdomain.conf.sample is currently missing the two final lines commencing with proxy_set_header.

**Comment by aptalca** [comment]
Those are set by default in SWAG
