### ISSUE TITLE
Request for Omada Controller

### ISSUE THREAD

**Issue by sarvesh-lad** [linuxserver/reverse-proxy-confs#460]
Hi,

Can we get a RP config for https://github.com/mbentley/docker-omada-controller ?

Regards

**Comment by j0nnymoe** [comment]
We take community submitted PR's as that'll likely be quicker (don't think anyone runs omada currently within the team.)

**Comment by sarvesh-lad** [comment]
> We take community submitted PR's as that'll likely be quicker (don't think anyone runs omada currently within the team.)

I think I got it working but login is weird so it is failing for me.
