### ISSUE TITLE
Update to vaultwarden/bitwarden proxy configs after valutwarden goes from 1.25.0 to 1.25.1

### ISSUE THREAD

**Issue by githubbiswb** [linuxserver/reverse-proxy-confs#463]
https://github.com/dani-garcia/vaultwarden/issues/2625
I have the issue explained out in a lot more detail in that github issue where we find the following lines need added into the /notifications/hub section
`  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";`
I actually added them to all of my sections on the valutwarden config and it doesn't seem to have caused any issues and it is also what the maintainer of the valutwarden container recommends
https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples - Nginx (by blackdex)

If this issue remains unfixed it didn't seem to affect the application functioning but did fill the logs when clients were connected with the following error

`
2022/07/18 13:22:47 [error] 527#527: 9949 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: bitwarden., request: "GET /notifications/hub?access_token=biglongrandomtokenhere HTTP/1.1", upstream: "http://192.168.255.70:3012/notifications/hub?access_token=biglongrandomtokenhere`

**Comment by githubbiswb** [comment]
The other repo pointed out these changes are also in your configs so it seems my proxy.conf fell behind the master config, and my guess is with those changes in the master it wouldn't need it in vaultwarden config. So I will have to test that new proxy config in my setup, so closing this for now as won't fix, since it looks like it is probably already fixed.

**Comment by nemchik** [comment]
Glad you figured it out. FYI we do make efforts to check if your confs are behind and log to the container log (`docker logs swag`). Instructions for updating configs are here https://github.com/linuxserver/docker-swag#updating-configs
