### ISSUE TITLE
[REQUEST] Librepeed subfolder config

### ISSUE THREAD

**Issue by PrivatePasta** [linuxserver/reverse-proxy-confs#478]
LSIO already has a [subdomain conf](https://github.com/linuxserver/reverse-proxy-confs/blob/master/librespeed.subdomain.conf.sample) for Librespeed so I'd like to request a subfolder config for those of us who prefer subfolders over subdomains. I've tried just changing the location but it seems some more work is needed.

So, if I change the location, I am able to see Librespeed in the subfolder, but I cannot actually do anything in it. Pressing the Start button doesn't do anything so I can only assume the config is wrong because going to the ip:port works just fine.

I know this is possible because Swizzin (a seedbox/server setup script similar to QuickBox or SaltBox) is able to do this. They use a different nginx config as you can see [here](https://github.com/swizzin/swizzin/blob/master/scripts/nginx/librespeed.sh). As far as I know they do not change anything on Librespeed's but I may be wrong.

**Comment by drizuid** [comment]
You're welcome to PR one after getting it to work. We, on the team, generally recommend using subdomain and are unlikely to put any time into this ourselves. You also need to ensure librespeed supports subfolder proxying. While subdomain works on everything, subfolder only works on apps that support it.
