### ISSUE TITLE
Plex Subdomain Remote Access Drops

### ISSUE THREAD

**Issue by bconn98** [linuxserver/reverse-proxy-confs#490]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I am migrating my plex instance to plex subdomain and am seeing the remote access being successful for ~3-10 seconds and then I lose it. The only way to get remote access back is to toggle the settings, but again it doesn't last.

I have the custom server access url set to https://plex.my-server.net:443, and have tried setting the remote access port to 443, 80, and not having it set.

Host OS: Ubuntu 20.04 LTS

No relevant logs.

No symlinks.

**Comment by aptalca** [comment]
If you're reverse proxying, you can turn the `remote access` setting in the gui off. It's only used for direct port forwarding to plex, not reverse proxy. If you're not port forwarding to plex (you shouldn't be), plex won't be able to make the traditional `remote access` connection and will disable it. That's fine and is expected.

**Comment by bconn98** [comment]
Does this mean that using the reverse proxy breaks compatibility with the plex apps?

**Comment by aptalca** [comment]
No. `remote access` and reverse proxy are different things as far as Plex is concerned. İf you're doing reverse proxy, setting the custom access urls will tell the woods how to access the server
