### ISSUE TITLE
Newest nextcloud.sub*.conf.samples not downloading/updating

### ISSUE THREAD

**Issue by cravas** [linuxserver/reverse-proxy-confs#504]
After seeing the latest update on the nextcloud.sub* samples, ran:
`docker-compose pull swag`
`docker restart swag`

But the samples aren't beeing updated.
Tried to delete the old samples, and it still pulled the same one's and NOT the updated version.

Please feel free to ask for any logs/commands/screenshots, if needed.

**Comment by msvarovsky** [comment]
Hi,
I have the same problem.
The log is reporting "emerg" errors even on rows which don't exist anymore. (e.g.: "...unexpected "}"..." error on row 43 of a file having only 40 rows.)

**Comment by cravas** [comment]
> I have the same problem.

This has nothing to do with what I reported.
What was happening was the samples weren't beeing updated with the newest versions, NOT emerg errors.

Your case is completly different.

If you say the file has 40 rows means you're using the nextcloud.subfolder.conf, correct?

Can you post the output of
`cat <path-to-swag-proxy-confs>/nexcloud.subfolder.conf.sample`
`cat <path-to-swag-proxy-confs>/nexcloud.subfolder.conf`
`ls -al <path-to-swag-proxy-confs>/nexcloud.sub*`

**Comment by msvarovsky** [comment]
Hi,
Thanks for the swift response.

> This has nothing to do with what I reported.
What was happening was the samples weren't beeing updated with the newest versions, NOT emerg errors.

I guess it's possible it's two different issues. I've mentioned the emerg error **only to illustrate** that I don't believe it was my conf file which had all those errors.

> If you say the file has 40 rows means you're using the nextcloud.subfolder.conf, correct?

No, it was the subdomain file, but the 40 and 43 numbers were chosen, again, only to illustrate that the error could not have coming out it.

Anyway, I solved the issue by getting the 1.32.0 version where it works perfectly.
Again, it might be that these are different issues and my message was not posted in the right issue. (Sorry if that is the case) Thank you nonetheless.
