### ISSUE TITLE
minor tweaks

### ISSUE THREAD

**Issue by kcris** [linuxserver/reverse-proxy-confs#506]
Thanks for the samples!!

1. I would add a note in the readme explaining that the subdomain install needs 
* additional DNS configuration (extra records for each of your subdomains)
* if using https, you also need to make sure that your certificate's CN covers those DNS entries

2. The provided samples use some common nginx configuration files that are not present in this repo.
Those should be included here too, right?

e.g. tvheadend sample refers to `/config/nginx/proxy.conf;` or `/config/nginx/resolver.conf;`

my guess is that you have samples/defaults for those as well

Thanks

**Comment by Roxedus** [comment]
Point 1 is documented in nearly all subdomain config files, a how-to is outside the scope of this, and the swag repo.
Point 2 is due to the fact that this repo is made to be used in swag, where these files are present.
