### ISSUE TITLE
[FEAT] add Strict-Transport-Security and X-Frame-Options headers to default nextcloud config

### ISSUE THREAD

**Issue by derekpurdy** [linuxserver/reverse-proxy-confs#515]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add the following headers to the default nextcloud config

```
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";
```

### Reason for change

Within Nextcloud, on the Administration Overview page, the following section "Security & setup warnings" warns of security issues.

_There are some warnings regarding your setup._
```
The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the [security tips ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-security).
```

### Proposed code change

Add the following headers to the default nextcloud config under the location section

```
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header X-Frame-Options "SAMEORIGIN";
```

**Comment by thespad** [comment]
We won't add HSTS as enabled by default, it will cause too many issues for people who don't realise it's in place or how it works.

X-Frame-Options is already part of the default conf: https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/nginx/site-confs/default.conf.sample#L52

**Comment by derekpurdy** [comment]
Thanks for the quick response @thespad

It appears that the part you menioned as already being part of the config is in the docker-nextcloud container and not being pulled down by swag.

perhaps, I'm just confused. I'm only getting this version

https://github.com/linuxserver/reverse-proxy-confs/blob/master/nextcloud.subdomain.conf.sample

**Comment by aptalca** [comment]
It's the nginx conf that the nextcloud container uses to serve its gui. Nothing to do with SWAG.

**Comment by derekpurdy** [comment]
> It's the nginx conf that the nextcloud container uses to serve its gui. Nothing to do with SWAG.

I run swag in my environment and it throws the warning mentioned above when behind the reverse proxy. So I'm just saying the error above is what I get unless I add those lines into my proxy-confs in the swag container.

**Comment by aptalca** [comment]
Headers can be and are set by either nextcloud's nginx, or SWAG's. In this case, those headers are expected to be set by nextcloud's nginx (except HSTS is not enabled by default because it is a sledgehammer).

If your nextcloud conf does not have the X-frame-option set to SAMEORIGIN, then update your conf as described in its readme.  If it does, but you're still getting the error, you likely have the same header set in SWAG, but with a different value.
