### ISSUE TITLE
[FEAT] Add coder.subdomain.conf.sample to proxy confs

### ISSUE THREAD

**Issue by paviln** [linuxserver/reverse-proxy-confs#559]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Make a proxy confs sample for coder, there is currently only one for coder-server.

### Reason for change

To have a working sample, can't get the proposed code change to work.

### Proposed code change

```
server {
    # HTTP configuration
    listen 80;
    listen [::]:80;

    # HTTP to HTTPS
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }

    # HTTPS configuration
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;

    server_name coder.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # Allow access to coder
    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app coder;
        set $upstream_port 3000;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**Comment by nemchik** [comment]
If you follow the template https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample you should be able to create a working proxy. You could even submit a pull request for it to be included here. Otherwise one of us can probably add it soon-ish and ping you to test.

**Comment by paviln** [comment]
@nemchik Thanks for your replay. I will give it a try, and get back to you.
