### ISSUE TITLE
[BUG] Filebrowser proxy config uses wrong default port

### ISSUE THREAD

**Issue by IevgenSobko** [linuxserver/reverse-proxy-confs#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, 8080 port used in proxy file configuration, so you need to go and change it to default 80

### Expected Behavior

Proxy should work without need to go and change port from 8080 to 80 in proxy configuration file

### Steps To Reproduce

Even if you deploy filebrowser container and try to change port to 8080 default healthcheck from image will ping 80 port
`Failed to connect to localhost port 80 after 0 ms: Connection refused`

**Comment by aptalca** [comment]
Which proxy conf is this about? I don't see one for `fileserver`

**Comment by billbrod** [comment]
I had this same problem -- switching the ports from 8080 to 80 fixed it.

**Comment by IevgenSobko** [comment]
Lets hope pull request will be accepted.
