### ISSUE TITLE
[FEAT] [FEAT] include /config/nginx/custom-confs/*.conf

### ISSUE THREAD

**Issue by quorn23** [linuxserver/reverse-proxy-confs#616]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Addition of `include /config/nginx/custom-confs/*.conf` in the provided proxy confs.

### Reason for change

Currently if a proxy config gets updated and Swag notifies on start up, there is no quick way to update proxy confs with custom config added. 
Simply changing the date in the header is not really a solution, as the configs should be kept up to date with other changes/updates in Swag.

Introducing the ability to have custom confs included in the server blocks by default would allow to update the proxy confs detached from any custom additions.

### Proposed code change

Add a `/nginx/custom-confs` folder to swag
Add `include /config/nginx/custom-confs/*.conf` to the server blocks of the proxy confs provided

**Comment by quorn23** [comment]
Happily provide more feedback if needed

**Comment by nemchik** [comment]
Could you give a more detailed example of what you're describing?

I don't think we'll make a change like this, but could at least discuss how you might be able to come close with your own configurations in the easiest way possible
