### ISSUE TITLE
[BUG] komga, remove /api block

### ISSUE THREAD

**Issue by FrenchGithubUser** [linuxserver/reverse-proxy-confs#620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the last block for /api is not needed and makes the initial register page not work (there is no "create account" button anymore)

### Steps To Reproduce

Run latest komga release with swag

**Comment by nemchik** [comment]
I am a bit confused why this would make a button not appear. The api endpoint is proxied the same way that the main location is. The documentation does indicate that there is an `/api` endpoint, and in general we include these as a way to allow access to an api without additional proxy auth configurations.

**Comment by FrenchGithubUser** [comment]
I don't know either. I simply know that after removing it it worked, and that the button was not here with /api.

Also, the example reverse proxy conf does not have /api
