### ISSUE TITLE
[BUG] Jellyfin gives an error 27 on specific devices

### ISSUE THREAD

**Issue by HammyHavoc** [linuxserver/reverse-proxy-confs#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current config gives an error 27 on specific devices. The solution is here and means the config file needs updating: https://jellyfin.org/docs/general/networking/nginx/

### Expected Behavior

Not get an error 27

### Steps To Reproduce

Try connecting to Jellyfin with a webOS device.

**Comment by HammyHavoc** [comment]
Still a problem.

**Comment by j0nnymoe** [comment]
If you've found a solution, please at least enlighten us or submit a PR fixing it.

**Comment by HammyHavoc** [comment]
> If you've found a solution, please at least enlighten us or submit a PR fixing it.

I haven't found any solution at present short of not using webOS devices.

**Comment by j0nnymoe** [comment]
> The current config gives an error 27 on specific devices. The solution is here and means the config file needs updating: https://jellyfin.org/docs/general/networking/nginx/

You said the solution is here, have you tried applying any of that first?

**Comment by HammyHavoc** [comment]
> > The current config gives an error 27 on specific devices. The solution is here and means the config file needs updating: https://jellyfin.org/docs/general/networking/nginx/
> 
> You said the solution is here, have you tried applying any of that first?

No, because I don't have a webOS device to test it with myself.

**Comment by j0nnymoe** [comment]
I would've assumed that because you reported the issue, that you were able to recreate it.

**Comment by HammyHavoc** [comment]
> I would've assumed that because you reported the issue, that you were able to recreate it.

Relatives with webOS who live a significant distance from me and are very old are likely not to be the most helpful in ongoing testing, but I have seen the problem first-hand.

I figured someone else must have the same issue.
