### ISSUE TITLE
[FEAT] amp by cubecoders

### ISSUE THREAD

**Issue by binarygeek119** [linuxserver/reverse-proxy-confs#631]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

i need a proxy config for swag to work with amp. i cant find a proxy online anywhere for amp.
https://cubecoders.com/AMP

### Reason for change

i require one

### Proposed code change

new config

**Comment by j0nnymoe** [comment]
Majority of our configs are community provided. I would recommend using the template we provide and see how you get on. 

If you report back with any issues, we can try to help.
