### ISSUE TITLE
[FEAT] Add support for GLPI

### ISSUE THREAD

**Issue by HammyHavoc** [linuxserver/reverse-proxy-confs#647]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

A config for https://glpi-project.org/

### Reason for change

GLPI is sweet.

**Comment by HammyHavoc** [comment]
Still interested.

**Comment by HammyHavoc** [comment]
Still interested.

**Comment by j0nnymoe** [comment]
Configs are generally added by the community unless it's an app we've released or use ourselves. 

If you've already got GLPI running, try and make one with the example template we provide.
