### ISSUE TITLE
[FEAT] Add support for OpenSSH-Server

### ISSUE THREAD

**Issue by nothing2obvi** [linuxserver/reverse-proxy-confs#679]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be really great if you could add an OpenSSH-Server config file.

### Reason for change

OpenSSH-Server is a docker image provided by LinuxServer, so I was actually expecting a config file to be available, but it is not. I find going through the NGINX documentation to be very confusing and I don't want to mess up the subdomain template in any way that would break what I am trying to accomplish.

### Proposed code change

No

**Comment by Roxedus** [comment]
SSH cannot be proxied over http, which is what this repo targets.
