### ISSUE TITLE
Jellyfin subfolder  config : Unable to find the specified file

### ISSUE THREAD

**Issue by snow3461** [linuxserver/reverse-proxy-confs#68]
Setting up jellyfin with subfolder config. I get this message in browser : Unable to find the specified file

Other services are configured as subfolder and are working.
Can reach jellyfin webui if I map the port and reach it by ip address. Tried to change public https to 443, and "handled by reverse proxy", with no success.

@CHBMB  Did you encounter this when you created the config?

**Comment by tobbenb** [comment]
Please provide how you deployed jellyfin and the prox-conf you are using.

**Comment by snow3461** [comment]
Deployment done with docker-compose. 

Here is the relevant part of of `docker-compose.yml` :

    version: '2.2'
    services:
        letsencrypt:
            image: linuxserver/letsencrypt
            container_name: letsencrypt
            networks:
                - net
            cap_add:
                - NET_ADMIN
            restart:
                always
            environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}
                - URL=${URL}
                - SUBDOMAINS=www,heimdall,
                - VALIDATION=duckdns
                - DUCKDNSTOKEN=${TOKEN}
                - DHLEVEL=2048 #optional
            volumes:
                - ${USERDIR}/letsencrypt/config:/config
            ports:
                - '443:443'
                - '80:80'
        jellyfin:
            image: linuxserver/jellyfin:latest
            container_name: jellyfin
            networks:
                - net
            volumes:
                - ${USERDIR}/jellyfin/config:/config
                - ${MOVIES}:/data/movies
                - ${TVSERIES}:/data/tvshows
            restart:
                always
            environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}
            ports:
                - 8096:8096
    networks:
        net:
            driver: bridge
            ipam:
                driver: default
                config:
                    - subnet: ${subnet}
                     gateway: ${gateway}
            driver_opts:
                com.docker.network.bridge.name: "network_name"
                com.docker.network.bridge.enable_ip_masquerade: "true"

in `proxy-confs` folder,  renamed `jellyfin.subfolder.conf.sample` to `jellyfin.subfolder.conf`. No addition to this file.

Nothing in nginx access log.
In jellyfin log, immediately after trying to access it : ` [ERR] Could not find handler for "/jellyfin/"`

**Comment by tobbenb** [comment]
Did you set up jellyfin as instructed in the jellyfin proxy-conf?

**Comment by snow3461** [comment]
This is the actual config in jellyfin's advanced section ;

![bug_1](https://user-images.githubusercontent.com/12656492/59919428-af77a500-9427-11e9-946e-47e081a90d9c.jpg)
![bug_2](https://user-images.githubusercontent.com/12656492/59919430-b2729580-9427-11e9-8ea4-dd903af5fa8d.jpg)

**Comment by tobbenb** [comment]
Did you set the external domain to yours? Its empty in the screen shot.

**Comment by snow3461** [comment]
I didn't.
I tried now, saving, restarting the container, and still not working. Same message. Same log entry.
 *But I found the problem.*

Base url is hard-coded into jellybin, and is still `emby`. Modifying `jellyfin.subfolder.conf`, and replacing the url to `/emby/` is working.
ref: https://github.com/jellyfin/jellyfin/issues/337  https://github.com/jellyfin/jellyfin/issues/691

I could make a PR to this repo if its not an issue from linuxserver/jellyfin not beeing up-to-date (Ididnt check).

**Comment by aptalca** [comment]
@snow3461 It seems our jellyfin config needs a rewrite statement to reverse proxy without a root url. I'll whip something up and if you can test it and let us know, that would be great.

**Comment by aptalca** [comment]
@snow3461 please give this a try: https://github.com/linuxserver/reverse-proxy-confs/blob/aptalca-patch-4/jellyfin.subfolder.conf.sample

**Comment by snow3461** [comment]
I gave it a try, and its seems to be working now with jellyfin base url. At least to access the webui in a browser.
thanks @aptalca 

I can't figure out how to set it up with the android app, but that's jellyfin problem, i will ask on there github.

**Comment by balmha** [comment]
Hi, I have te same error, but my Jelly Server run on docker: 
sudo docker run --name jelly -d -v /srv/jellyfin/config:/config -v /srv/jellyfin/cache:/cache -v /media:/media --net=host jellyfin/jellyfin:latest

this is my nginx config, for security reasons i dont show my domain name:
```
server {
        server_name mydomain.com.ar subdomain.mydomain.com.ar; # managed by Certbot
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

	location /scrollmedia {
		proxy_pass http://localhost:8096;
	}

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com.ar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com.ar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by tobbenb** [comment]
@balmha I'm not sure what your post have to do with our proxy-confs as it's clear you are not using our proxy-conf.

**Comment by aptalca** [comment]
Or our image for that matter
