### ISSUE TITLE
[FEAT] Missing SearXNG config

### ISSUE THREAD

**Issue by isvein** [linuxserver/reverse-proxy-confs#717]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Adding config file for SearXNG
The config below works for me, looks like nothing else is needed.
Tested with SearXNG container from Unraid app-store

### Reason for change

Missing

### Proposed code change

```
# make sure that your searXNG container is named searxng
# make sure that your dns has a cname set for search

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name search.*;

    include /config/nginx/ssl.conf;

    location / {

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 192.168.40.17;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
```

**Comment by drizuid** [comment]
please submit this as a PR and ensure you follow the conf template as your base. confs are submitted by users, such as yourself, not by us, unless we use the application (in which case, we're just users)
