### ISSUE TITLE
Proxy subfolder config

### ISSUE THREAD

**Issue by judos** [linuxserver/reverse-proxy-confs#72]
Thanks for the great config guys!
I ran into some issues with the plex subfolder config though. I tried around for quite some time using a plain nginx instance (not the docker container) because of the otherwise working configs.

The subfolder configs seem to work as far as the website goes, however the connection always appears as indirect. Do you have anything else you tweaked in the nginx configs besides the location { ... } block I copied? I also added the proxy.conf from the repo into /etc/nginx/sites-available/ to make sure it imports the same as you do.

This is my /etc/nginx/sites-available/mydomain.ddnss.ch.conf: https://pastebin.com/V90Zzwyc
And also the proxy.conf: https://pastebin.com/YqRgWnz9

I would be very glad for any help if you happen to know what the issue could be.

**Comment by aptalca** [comment]
The default configs are in our letsencrypt image here: https://github.com/linuxserver/docker-letsencrypt/tree/master/root/defaults

Only thing I can think of is that you're using the IP for the proxy and not a hostname based variable.

Try removing the rewrite line above proxy_pass and add a trailing slash to the end of the plex proxy_pass ip:port

**Comment by judos** [comment]
Yes the default config I found, so that should be good.

You mean to change it like this?
```
       location ^~ /plex/ {

            include /etc/nginx/sites-available/proxy.conf;
            resolver 127.0.0.11 valid=30s;
            set $upstream_plex plex;
            proxy_pass http://127.0.0.1:32400/;

            proxy_set_header ...
```

Doesn't seem to change anything, still an indirect connection. Do I need to forward specific ports? Actually running plex on domain root path it works, so ports don't seem to be the issue...

**Comment by aptalca** [comment]
Did you add the custom access url to plex settings?

I can't really help you any further. When running in our docker image, this config works fine.

**Comment by judos** [comment]
hmm yeah I did that, ok so I will try again from scratch with this docker image. When I find out more i'll post it. Thanks for the help so far. If it becomes too complicated i'll switch to the subdomain approach though, looks like people have less issues there...
