### ISSUE TITLE
[FEAT] Netbird vpn config

### ISSUE THREAD

**Issue by wakawakaaa** [linuxserver/reverse-proxy-confs#725]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please include Netbird VPN config

### Reason for change

Missing config

**Comment by drizuid** [comment]
feel free to use our template to create one, once you have it working, you can PR it to us.

**Comment by npcraft** [comment]
I have a working version of Netbird Nginx configs for Swag, I will test it few days more and create a pull request. 
by the way I have already working version of Headscale configs, created a pull request, which is also nice alternative of Netbird. Take a look here: https://github.com/linuxserver/reverse-proxy-confs/pull/727
