### ISSUE TITLE
Setup plex config

### ISSUE THREAD

**Issue by judos** [linuxserver/reverse-proxy-confs#73]
Ok I retried the plex subfolder config with the linuxserver/docker-letsencrypt image but I get stuck earlier.

So basically I setup the image :
```
docker run \
  --name=nginx_letsencrypt \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e URL=mydomain \
  -e VALIDATION=http \
  -e EMAIL=myemail \
  -e DHLEVEL=2048 `#optional` \
  -e ONLY_SUBDOMAINS=false `#optional` \
  -e STAGING=false `#optional` \
  -p 443:443 \
  -p 80:80 `#optional` \
	--network=mydockernetwork \
  -v /hd/nginx_letsencrypt:/config \
  --restart unless-stopped \
  linuxserver/letsencrypt
```

That looks fine so far and I can reach the server with https and it shows a nice "Welcome to our server". Then I try to setup plex as follow:
```
cp plex.subfolder.conf.sample plex.subfolder.conf
docker restart nginx_letsencrypt 
```

Plex container is running fine and I can reach it via http://$ip:32400
But via mydomain/plex it returns a 500 gateway error.

So I read further on the readme here "Ensure you have a custom docker network" that I should create a custom docker network for plex. So I do that:
`docker network create mydockernetwork`
And recreate the plex container using just `--network=mydockernetwork`, no port mapping. Before I was using `--network=host`

How should the nginx_letsencrypt container now know to use this network?
It doesn't say where else the network should be used or given as parameter.

And still plex is not reachable via mydomain/plex -> 502 Bad Gateway nginx/1.14.2
Also plex is now not reachable via http://$ip:32400.
I don't know how docker networks are working, do you have a hint what I did wrong?

Thanks a lot!

**Comment by tobbenb** [comment]
Please use our forum or Discord for support questions. This place is for reporting bugs.

https://discourse.linuxserver.io
https://discord.gg/YWrKVTn
