### ISSUE TITLE
TVheadend

### ISSUE THREAD

**Issue by jobrien2001** [linuxserver/reverse-proxy-confs#77]
Any chance to include encryption for TVH (the http side of it port 9981)?

**Comment by aptalca** [comment]
We currently don't provide preset proxy confs for TVH. Can't remember if someone tried and failed or if no one has tried it.

I'll ask in our discord channel

**Comment by tobbenb** [comment]
I haven't tried. Not sure what is possible either.

**Comment by jobrien2001** [comment]
Found this in their FAQ
```
Q: Access Tvheadend through HTTP proxy
Use '--http_root' directive to specify the alternative http webroot (initial path prefix). The proxy server MUST pass this webroot path in the HTTP request, otherwise an access to the Tvheadend server will end with the endless redirect loop.

Example for nginx (--http_root /my/tvh/server):

	location /my/tvh/server {
		proxy_pass http://1.1.1.1:9981;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
Example for apache (--http_root=/my/tvh/server):

ProxyPass "/my/tvh/server" "http://1.1.1.9981/my/tvh/server";
```

**Comment by drdebian** [comment]
> Found this in their FAQ
> 
> ```
> Q: Access Tvheadend through HTTP proxy
> Use '--http_root' directive to specify the alternative http webroot (initial path prefix). The proxy server MUST pass this webroot path in the HTTP request, otherwise an access to the Tvheadend server will end with the endless redirect loop.
> 
> Example for nginx (--http_root /my/tvh/server):
> 
> 	location /my/tvh/server {
> 		proxy_pass http://1.1.1.1:9981;
> 		proxy_set_header Host $host;
> 		proxy_set_header X-Real-IP $remote_addr;
> 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection "upgrade";
> 	}
> Example for apache (--http_root=/my/tvh/server):
> 
> ProxyPass "/my/tvh/server" "http://1.1.1.9981/my/tvh/server";
> ```

Has anybody managed to get this working with .htpasswd basic authentication on top? Just adding the commented out statements doesn't do it, but instead yields 403 errors... Any ideas?

**Comment by j0nnymoe** [comment]
CLosing as solution was provided https://github.com/linuxserver/reverse-proxy-confs/issues/177
