### ISSUE TITLE
Plex subdomain config issue

### ISSUE THREAD

**Issue by jruben4** [linuxserver/reverse-proxy-confs#78]
using letsencrypt community app on unraid for reverse proxy, working OK for nextcloud. Trying to set it up for plex too. The only thing I changed in the plex.subdomain.conf file is

proxy_pass https://$upstream_plex:32400;

since I am requiring secure connections.

This setup works locally (plex.mydomain.com) on a web browser but doesn’t seem to work for my devices. Also plex says it can’t be reached from the network.

**Comment by aptalca** [comment]
Did you add `https://plex.domain.com:443` to Custom Access URLs in plex server settings? That's the address plex advertises to the devices

**Comment by jruben4** [comment]
Yes I did.

**Comment by thelamer** [comment]
Do the devices you are connecting support secure connections ? Older gen stuff does not even without a proxy in place just raw Plex secure connections.

**Comment by aptalca** [comment]
No response, closing. Likely settings issue, or hairpin nat not allowing clients to access plex at domain url.
