### ISSUE TITLE
Feature Request - Monica CRM Subfolder/Subdomain examples

### ISSUE THREAD

**Issue by spoonefl1** [linuxserver/reverse-proxy-confs#86]
I've generally been able to create my own .conf files when I've needed to, but I'm seriously struggling with creating a new subfolder.conf for Monica CRM: https://github.com/monicahq/monica

I've seen example nginx.conf files for it, but I've yet to be able to extract what I need from them to make it work properly. Examples here: https://www.vultr.com/docs/how-to-install-monica-on-ubuntu-18-04-lts and here: https://github.com/monicahq/monica/issues/568 and a Yunohost version here: https://github.com/YunoHost-Apps/monica_ynh/blob/master/conf/nginx.conf

The best I've managed is:
```
location /monica {
    return 301 $scheme://$host/monica/;
}
location ^~ /monica/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_monica monicahq;
    rewrite /monica(.*) $1 break;
    proxy_pass http://$upstream_monica:80;
    proxy_redirect off;
    proxy_set_header Host $host;

#    proxy_set_header Range $http_range;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
#    proxy_set_header X-Forwarded-Host $server_name;
}
```

The login page loads, but incorrectly, with images and css pointing to their original paths, rather than under Monica, and login fails as it tries to load example.com/login in stead of example.com/monica/login

Apologies if I handled this incorrectly, and thanks in advance for any help you can offer.

**Comment by aptalca** [comment]
According to [here](https://github.com/monicahq/monica/issues/139) you need to set APP_URL correctly in monica
