### ISSUE TITLE
Host not found

### ISSUE THREAD

**Issue by viruz82** [linuxserver/reverse-proxy-confs#87]
Hello,

I have a lot of services running and a cname for all in my dns config (bind9). When I open the url in my browser nginx says:  `2019/09/03 08:03:06 [error] 368#368: *5 wordpress could not be resolved (3: Host not found)...`

nslookup lookes wired but can resolve the hostname:

> root@ebcdbc201640:/# nslookup wordpress
> nslookup: can't resolve '(null)': Name does not resolve
> 
> Name:      wordpress
> Address 1: 10.10.10.12 docker2.domain.com`

Ping looks good:

> root@ebcdbc201640:/# ping -c 3 wordpress
> PING wordpress (10.10.10.12): 56 data bytes
> 64 bytes from 10.10.10.12: seq=0 ttl=64 time=0.032 ms
> 64 bytes from 10.10.10.12: seq=1 ttl=64 time=0.056 ms
> 64 bytes from 10.10.10.12: seq=2 ttl=64 time=0.045 ms

And this is the resolv.conf of my container:

> search domain.com
> nameserver 127.0.0.11
> options ndots:1

Any ideas what I'm doing wrong?

Cheers
Kai

**Comment by tobbenb** [comment]
I'm not sure why you have made this issue as this is not related to  our proxy configs. We don't have any WordPress config.
This is not a support channel.

**Comment by viruz82** [comment]
Oh man this was just an example! I have the problem with all of your configs. Need another example?
This also doesn't work for me:

```
# make sure that your dns has a cname set for www and that your www container is not using a base url

server {
    listen 443 ssl;

    server_name www.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_www www;
        proxy_pass http://$upstream_www:83;
    }
}
```



> This is not a support channel.

And where else should I post my problems with your configs?!

**Comment by j0nnymoe** [comment]
That's not one of our example config's either?

**Comment by tobbenb** [comment]
Support is done on discord or discourse (our forum). This is reserved for bugs.
