### ISSUE TITLE
Jeedom proxy-conf

### ISSUE THREAD

**Issue by yan-064** [linuxserver/reverse-proxy-confs#96]
Hi,

Is it possible to add the jeedom.subfolder.conf file ? It works good with portainer, nextcloud and other. So I tried to do myself with the other sample but it works bad, it's slow and a lot of 502/504 errors happened.

`
location /jeedom {
    return 301 $scheme://$host/jeedom/;
}

location ^~ /jeedom/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jeedom 192.168.1.31;
    rewrite /jeedom(.*) $1 break;
    proxy_pass http://$upstream_jeedom:9080;

    proxy_max_temp_file_size 1024m;

    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_set_header Connection $http_connection;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}
`

By using local ip there is no problem.

Thanks.

**Comment by yan-064** [comment]
Hi,

I tried with a simpliest configuration and I took bad request error (400) from the jeedom server. I don't how to investigate.

Help will be appreciated, thanks.

`location /jeedom {
    return 301 $scheme://$host/jeedom/;
}

location ^~ /jeedom/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jeedom 192.168.1.31;
    rewrite /jeedom(.*) $1 break;
    proxy_pass http://$upstream_jeedom:9080;
}`

**Comment by moarf56** [comment]
Hi, do you find a solution ?

Because I use jeddom on another computer and I want use my letsencrypt container for reverse the traffic too !
I already use letsencrypt container for nexctcloud, ombi ... All are inthe same computer execpt jeedom.

Thx

**Comment by yan-064** [comment]
> Hi, do you find a solution ?
> 
> Because I use jeddom on another computer and I want use my letsencrypt container for reverse the traffic too !
> I already use letsencrypt container for nexctcloud, ombi ... All are inthe same computer execpt jeedom.
> 
> Thx

Hi,

No, I'm still in trouble. For the moment, I only use Jeedom locally. Even the Jeedom community can't help me. 

It bothers me, I'm too newb to understand what's happen.

If you find solutions, please post here.

Thanks.

**Comment by metroveinte** [comment]
Also interested getting this config, i´m on the same problem.

**Comment by yan-064** [comment]
Hi,

I updated my hardware with a rasp4 and this configuration seems to work fine :

location /jeedom {
    return 301 $scheme://$host/jeedom/;
}

location ^~ /jeedom/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jeedom 192.168.1.74;
    rewrite /jeedom(.*) $1 break;
    proxy_pass http://$upstream_jeedom:9080;
}

**Comment by moarf56** [comment]
Hi !

Glad to learn that !! But How did you do ?
Because normaly I create a new fil in /nginx\site-confs/ of the docker container and put the code inside.
The code is like this (this is my nextcloud config file): 
```
server {
    listen 443 ssl;

    server_name nc.*;
add_header X-Robots-Tag "nofollow, nosnippet, noarchive, none";
    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_nextcloud nc;
        proxy_max_temp_file_size 2048m;
        proxy_pass https://192.168.0.100:9443;
```

Thx :d

**Comment by yan-064** [comment]
Hi,

I created a file (with the configuration above) named jeedom.subfolder.conf into config/nginx/proxy-confs. I didn't change the site-confs because it already includes all the subfolder.conf files:

```
        # enable subfolder method reverse proxy confs
        include /config/nginx/proxy-confs/*.subfolder.conf;
```
Here, it still works great. 

Hope it helps.

**Comment by j0nnymoe** [comment]
If someone here has a working config for this, please submit a PR to this repo for it.
