### ISSUE TITLE
Grafana login loop using ldap-auth

### ISSUE THREAD

**Issue by jt70471** [linuxserver/reverse-proxy-confs#99]
Hi, I'm trying to use the linuxserver ldap-auth to front end all of my containers. It seems that Grafana uses a /login URI for its own authentication. I tried to implement the suggestion stated in issue #60 which is has been closed.

Hi, I tried this, unfortunately it still doesn't work. Instead of being directed to the ldap-auth login page, I get a result that just says: Hello, world! Requested URL: /ldaplogin

Here's my updated grafana.subdomain.conf:

```
server {
    listen 443 ssl;
#   listen [::]:443 ssl;

    server_name grafana.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    include /config/nginx/ldap.conf;
    include /config/nginx/ldap2.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        auth_request /auth;
        error_page 401 =200 /ldaplogin;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $upstream_grafana [redacted];
        proxy_pass http://$upstream_grafana:3000;
    }
}
```

And the new location I added to ldap2.conf:

```
location /ldaplogin {
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $upstream_ldap [redacted];
        proxy_pass http://$upstream_ldap:9001;
        proxy_set_header X-Target $request_uri;
    }
```

**Comment by aptalca** [comment]
Just realized `/login` is hardcoded in ldap-auth https://github.com/linuxserver/docker-ldap-auth/blob/master/root/app/ldap-backend-app.py#L30
I'll see what I can come up with

**Comment by aptalca** [comment]
@jt70471 I realize it's a long time later, but this was actually fixed a while back on both the ldap-auth image and in the proxy-confs here. Feel free to reopen if you're still having issues
